spring:
  datasource:
    # url
    url: jdbc:postgresql://localhost:5432/testdb
    # db name
    username: testuser
    # db password
    password: testpass
    # db driver
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false