spring:
  datasource:
    # url
    url: jdbc:h2:tcp://localhost/~/test
    # db name
    username: sa
    # db password
    password:
    # db driver
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  profiles:
    active: local