spring:
  datasource:
    # url
    url: jdbc:h2:tcp://localhost/~/test
    # db name
    username: sa
    # db password
    password:
    # db driver
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
#    open-in-view: false  open-in-view 를 false 로 설정하면 컨트롤러에서 리포지토리를 직접 통해 엔티티를 조회해도 엔티티 매니저가 관리하지 않는다.
